'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {api,session} from '@/lib/api';

export default function Projects(){
 const[items,setItems]=useState<any[]>([]),[trash,setTrash]=useState<any[]>([]),[loading,setLoading]=useState(true),[voice,setVoice]=useState('ALL'),[status,setStatus]=useState('ALL'),[country,setCountry]=useState('ALL'),[showTrash,setShowTrash]=useState(false);
 async function load(){setLoading(true);try{const[active,deleted]=await Promise.all([api<any[]>('/projects'),api<any[]>('/projects/trash'),fetch('/api/video-trash',{cache:'no-store'})]);setItems(active);setTrash(deleted)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const countries=[...new Set(items.map(p=>p.country||'GLOBAL'))],voices=[...new Set(items.map(p=>p.voice))],shown=useMemo(()=>items.filter(p=>(voice==='ALL'||p.voice===voice)&&(status==='ALL'||p.status===status)&&(country==='ALL'||(p.country||'GLOBAL')===country)),[items,voice,status,country]);
 async function edit(p:any){const title=prompt('Update video title',p.title);if(title?.trim()){await api(`/projects/${p.id}`,{method:'PATCH',body:JSON.stringify({title:title.trim()})});load()}}
 async function visibility(p:any){await api(`/projects/${p.id}/visibility`,{method:'PATCH',body:JSON.stringify({visibility:p.visibility==='HIDDEN'?'VISIBLE':'HIDDEN'})});load()}
 async function moveFile(p:any,action:'trash'|'restore'){if(!p.finalVideoUrl)return p.finalVideoUrl;const token=session()?.accessToken,response=await fetch('/api/video-trash',{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({projectId:p.id,url:p.finalVideoUrl,action})}),data=await response.json();if(!response.ok)throw new Error(data.error);await api(`/projects/${p.id}/file-url`,{method:'PATCH',body:JSON.stringify({url:data.url})});return data.url}
 async function remove(p:any){if(!confirm('Move this video to Trash for 60 days? You can restore it during that period.'))return;try{await moveFile(p,'trash');await api(`/projects/${p.id}`,{method:'DELETE'});load()}catch(e){alert(e instanceof Error?e.message:'Unable to move video to Trash')}}
 async function restore(p:any){try{await moveFile(p,'restore');await api(`/projects/${p.id}/restore`,{method:'POST'});load()}catch(e){alert(e instanceof Error?e.message:'Unable to restore video')}}
 return <main className="module-page"><header><Link href="/">← Dashboard</Link><b>All Projects</b><span>{showTrash?`${trash.length} in trash`:`${shown.length} videos`}</span></header><section><p className="eyebrow">YOUR VIDEO LIBRARY</p><h1>{showTrash?'Trash':'Projects'}</h1><div className="project-filters"><button className={!showTrash?'active':''} onClick={()=>setShowTrash(false)}>Videos</button><button className={showTrash?'active':''} onClick={()=>setShowTrash(true)}>Trash ({trash.length})</button>{!showTrash&&<><select value={voice} onChange={e=>setVoice(e.target.value)}><option value="ALL">All voices</option>{voices.map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{['DRAFT','PROCESSING','COMPLETED','FAILED'].map(v=><option key={v}>{v}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)}><option value="ALL">All countries</option>{countries.map(v=><option key={v}>{v}</option>)}</select></>}</div>{loading?<div className="empty-projects">Loading projects…</div>:showTrash?<div className="video-library-grid">{trash.map(p=><article key={p.id}><div className="beautiful-player"><div><b>Stored in Trash</b><span>Permanent deletion {new Date(p.purgeAfter).toLocaleDateString()}</span></div></div><div className="video-meta"><b>{p.title}</b><small>{Math.max(0,Math.ceil((new Date(p.purgeAfter).getTime()-Date.now())/86400000))} days remaining</small></div><div className="library-actions"><button onClick={()=>restore(p)}>Restore video</button></div></article>)}</div>:shown.length===0?<div className="empty-projects">No matching projects.</div>:<div className="video-library-grid">{shown.map(p=><article key={p.id}><div className="beautiful-player">{p.finalVideoUrl?<video src={p.finalVideoUrl} controls preload="metadata"/>:<div><b>{p.status}</b><span>Video will appear here when rendering completes</span></div>}</div><div className="video-meta"><b>{p.title}</b><small>{p.language.toUpperCase()} · {p.format} · {p.voice} · {p.country||'GLOBAL'}</small><small>{new Date(p.updatedAt).toLocaleString()} · {p.creditsConsumed} credits · {p.viewCount||0} views</small><strong className={`status ${p.status.toLowerCase()}`}>{p.visibility==='HIDDEN'?'HIDDEN':p.status}</strong></div><div className="library-actions">{p.finalVideoUrl&&<a href={p.finalVideoUrl} download>Download</a>}<button onClick={()=>edit(p)}>Edit title</button><button onClick={()=>visibility(p)}>{p.visibility==='HIDDEN'?'Show video':'Hide video'}</button><button className="danger" onClick={()=>remove(p)}>Move to trash</button></div></article>)}</div>}</section></main>
}
