import { BadRequestException, Body, CanActivate, ConflictException, Controller, createParamDecorator, ExecutionContext, Get, Injectable, Patch, Post, UnauthorizedException, UseGuards } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { IsEmail, IsOptional, IsString, Length, MinLength } from 'class-validator';
import * as bcrypt from 'bcryptjs';
import { PrismaService } from './prisma.service';

export class RegisterDto { @IsString() @Length(2,80) fullName!:string; @IsEmail() email!:string; @IsOptional() @IsString() mobile?:string; @IsString() @MinLength(8) password!:string; @IsString() confirmPassword!:string }
export class LoginDto { @IsEmail() email!:string; @IsString() password!:string }

async function sendResetEmail(to:string, token:string){
 const base=(process.env.WEB_URL??'http://localhost:3000').split(',')[0].trim().replace(/\/$/,'');
 const resetUrl=`${base}/reset-password?token=${encodeURIComponent(token)}`;
 const resendKey=process.env.RESEND_API_KEY;
 const from=process.env.EMAIL_FROM||'Drishyana <onboarding@resend.dev>';
 if(!resendKey)return{sent:false,resetUrl};
 const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${resendKey}`,'content-type':'application/json'},body:JSON.stringify({from,to,subject:'Reset your Drishyana password',html:`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#1f1a2e"><h2>Reset your password</h2><p>We received a request to reset your Drishyana password.</p><p><a href="${resetUrl}" style="background:#7047d8;color:#fff;padding:12px 16px;border-radius:8px;text-decoration:none;font-weight:700">Reset password</a></p><p>This link expires in 1 hour. If you did not request this, you can ignore this email.</p></div>`,text:`Reset your Drishyana password: ${resetUrl}\n\nThis link expires in 1 hour.`})});
 if(!response.ok)throw new BadRequestException('Reset email could not be sent. Please check email provider settings.');
 return{sent:true,resetUrl};
}

@Injectable() export class JwtGuard implements CanActivate { constructor(private jwt:JwtService,private db:PrismaService){} async canActivate(ctx:ExecutionContext){const req=ctx.switchToHttp().getRequest(),token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!token)throw new UnauthorizedException('Authentication required');try{const payload=this.jwt.verify(token),account=await this.db.user.findUnique({where:{id:payload.sub},select:{id:true,email:true,role:true,status:true}});if(!account||account.status!=='ACTIVE')throw new UnauthorizedException('Account is not active');req.user={...payload,sub:account.id,email:account.email,role:account.role};return true}catch(error){if(error instanceof UnauthorizedException)throw error;throw new UnauthorizedException('Invalid or expired session')}} }
export const CurrentUser=createParamDecorator((_:unknown,ctx:ExecutionContext)=>ctx.switchToHttp().getRequest().user as {sub:string;role:string;email:string});

@Injectable() export class AuthService { constructor(private db:PrismaService,private jwt:JwtService){} async register(input:RegisterDto){if(input.password!==input.confirmPassword)throw new BadRequestException('Passwords do not match');const email=input.email.toLowerCase().trim();if(await this.db.user.findUnique({where:{email}}))throw new ConflictException('Email already registered');const user=await this.db.$transaction(async tx=>{const created=await tx.user.create({data:{fullName:input.fullName.trim(),email,mobile:input.mobile,passwordHash:await bcrypt.hash(input.password,12),emailVerificationToken:crypto.randomUUID(),profile:{create:{}}}});await tx.creditTransaction.create({data:{userId:created.id,amount:1000,direction:'CREDIT',type:'REGISTRATION',description:'Welcome credits',balanceAfter:1000}});return created});return this.session(user)} async login(input:LoginDto){const user=await this.db.user.findUnique({where:{email:input.email.toLowerCase().trim()}});if(!user||!await bcrypt.compare(input.password,user.passwordHash))throw new UnauthorizedException('Invalid email or password');if(user.status!=='ACTIVE')throw new UnauthorizedException('Account is not active');await this.db.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}});return this.session(user)} async me(id:string){const user=await this.db.user.findUniqueOrThrow({where:{id},select:{id:true,fullName:true,email:true,mobile:true,role:true,credits:true,status:true,emailVerified:true,createdAt:true}}),paid=await this.db.purchase.count({where:{userId:id,status:'SUCCEEDED'}});return{...user,hasPaid:paid>0||user.role==='ADMIN'}} async forgot(email:string){const user=await this.db.user.findUnique({where:{email:email.toLowerCase().trim()}});if(user){const token=crypto.randomUUID();await this.db.user.update({where:{id:user.id},data:{resetToken:token,resetTokenExpiresAt:new Date(Date.now()+3600000)}});const emailResult=await sendResetEmail(user.email,token);return{message:emailResult.sent?'Password reset link sent to your email.':'Reset created. Email is not configured on this environment.',token:process.env.NODE_ENV==='production'?undefined:token,resetUrl:process.env.NODE_ENV==='production'?undefined:emailResult.resetUrl}}return{message:'If the email exists, a reset link will be sent'}} async reset(token:string,password:string){const user=await this.db.user.findFirst({where:{resetToken:token,resetTokenExpiresAt:{gt:new Date()}}});if(!user)throw new BadRequestException('Invalid or expired reset token');await this.db.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(password,12),resetToken:null,resetTokenExpiresAt:null}});return{message:'Password updated'}} private session(user:{id:string;email:string;role:string;fullName:string;credits:number}){return{accessToken:this.jwt.sign({sub:user.id,email:user.email,role:user.role}),user:{id:user.id,email:user.email,role:user.role,fullName:user.fullName,credits:user.credits}}} }
@Controller('auth') export class AuthController { constructor(private service:AuthService,private db:PrismaService){} @Post('register')register(@Body()b:RegisterDto){return this.service.register(b)} @Post('login')login(@Body()b:LoginDto){return this.service.login(b)} @Post('forgot-password')forgot(@Body()b:{email:string}){return this.service.forgot(b.email)} @Post('reset-password')reset(@Body()b:{token:string;password:string}){return this.service.reset(b.token,b.password)} @Get('me')@UseGuards(JwtGuard)me(@CurrentUser()u:any){return this.service.me(u.sub)} @Patch('me')@UseGuards(JwtGuard)async update(@CurrentUser()u:any,@Body()b:{fullName?:string;mobile?:string}){if(!b.fullName?.trim())throw new BadRequestException('Full name is required');await this.db.user.update({where:{id:u.sub},data:{fullName:b.fullName.trim(),mobile:b.mobile?.trim()||null}});return this.service.me(u.sub)} }
